apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master
  labels:
    service: master
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        service: master
    spec:
      containers: 
      - name: master
        image: ros:kinetic
        ports:
        - containerPort: 11311
          name: master
        args:
        - roscore
