apiVersion: v1
kind: Service
metadata: 
  name: talker
spec:
  clusterIP: None
  ports: 
  # useless exposed port, just putting it as the master
  - port: 11311
    protocol: TCP
  selector: 
    service: talker
  type: ClusterIP
